### ISSUE TITLE
#FeatureRequest support encrypted images

### ISSUE THREAD

**Issue by romeokienzler** [kalbfuss/pyframe#1]
Would it be possible to implement an encryption mechanism (eg., using openssl or gpg sym/asym) to provide encrypted images on WebDAV such that unencrypted images don't need to be stored on cloud)

**Comment by kalbfuss** [comment]
Sounds like you are looking for client-side encryption of image data. I assume the purpose is to protect your images stored in a public cloud. In principle, this should be possible. My question would be how you want to upload those images? Pyframe currently does not help you with that. It only pulls files out of repositories, but does not upload them. Means you would need a separate application that implements the same type of client-side encryption and exchanges keys with Pyframe. That is not impossible, but sounds very cumbersome to me.
Could it be simpler for you to setup your own private cloud? This is what I do. I have my own instance of ownCloud running on an arm-based single-board computer, which is exposed to the internet for non-critical images. And I have a Synology NAS in my LAN, which is not exposed to the internet, but to which I regularly push new photos from my Smartphone via the Synology Photos app.

**Comment by romeokienzler** [comment]
@kalbfuss thanks for getting back

All my images are encrypted in the cloud anyway. I could just use a shell script (find, openssl). ATM I'm using rclone which has built-in support for encryption.

On the client side I'd suggest to just check if the (configurable) file extension is something like .enc. Then just use the python openssl implementation to decrypt.

Key can just be put as a file parallel to your application.

**Comment by kalbfuss** [comment]
Ok. That should be easy enough to achieve. The class repository.webdav.Repository would only need an additional configuration parameter, which provides the private/decryption key and decryption step after downloading the files. If only some files are encrypted then we also need a special file extension as you suggested or another way to recognize encrypted files.
Would you be able to provide me with a test environment and key?

**Comment by romeokienzler** [comment]
Sure would be some files and a key be sufficient? 

Or the openssl commands to create them?

I'm not fluent in WebDAV. I'm on COS (see #2 )

**Comment by kalbfuss** [comment]
All three would be ideal. However, if your files cannot be accessed via WebDAV, there is no point in implementing the requested feature at the moment. I am not planning to implement S3/COS support in the near future.

**Comment by romeokienzler** [comment]
OK I might be able to contribute this...

**Comment by romeokienzler** [comment]
Implemented by #2
